import {
  LayoutDashboard,
  Users,
  TrendingUp,
  Briefcase,
  FileText,
  Receipt,
  Truck,
  HardHat,
  Wrench,
  Layers,
  MessageSquare,
  Mail,
  MessageCircle,
  Building2,
  Megaphone,
  Percent,
  ClipboardList,
  Activity,
  Bell,
  LayoutTemplate,
  Gift,
  Boxes,
  ScrollText,
  BarChart3,
  Settings,
  Map,
  Trophy,
  ShieldCheck,
  AlertTriangle,
  Inbox,
} from "lucide-react";
import type { NavItem } from "@/types";

// Single source of truth for the app nav (used by both Sidebar and MobileNav).
// Mirrors the Base44 (crmazzy.com) left navigation.
export const NAV_ITEMS: NavItem[] = [
  { label: "Dashboard", href: "/dashboard", icon: LayoutDashboard },
  { label: "Customers", href: "/customers", icon: Users },
  { label: "Leads", href: "/leads", icon: TrendingUp },
  { label: "Quotes", href: "/quotes", icon: FileText },
  { label: "High-Value Commercial", href: "/high-value-commercial", icon: Building2, roles: ["admin", "user", "sales", "telesales"] },
  { label: "Services", href: "/services", icon: Layers, roles: ["admin", "user"] },
  { label: "Jobs", href: "/jobs", icon: Briefcase },
  { label: "Invoices", href: "/invoices", icon: Receipt },
  { label: "Field", href: "/field", icon: Wrench, roles: ["admin", "user", "operative"] },
  { label: "Fleet", href: "/fleet", icon: Truck, roles: ["admin", "user"] },
  { label: "Contractors", href: "/contractors", icon: HardHat, roles: ["admin", "user"] },
  { label: "Comms", href: "/comms", icon: MessageSquare, roles: ["admin", "user"] },
  { label: "Email Sequences", href: "/comms/sequences", icon: Mail, roles: ["admin", "user"] },
  { label: "Marketing Dashboard", href: "/marketing", icon: Megaphone, roles: ["admin", "user"] },
  { label: "Website Chat", href: "/website-chat", icon: MessageCircle, roles: ["admin", "user"] },
  { label: "Route Planning", href: "/route-planning", icon: Map, roles: ["admin", "user"] },
  { label: "Commissions", href: "/commissions", icon: Percent, roles: ["admin", "user"] },
  { label: "Commission Tracking", href: "/commission-invoices", icon: ClipboardList, roles: ["admin", "user"] },
  { label: "Performance", href: "/performance", icon: Trophy, roles: ["admin", "user"] },
  { label: "Team Output", href: "/team-output", icon: Activity, roles: ["admin", "user"] },
  { label: "Reminders", href: "/reminders", icon: Bell, roles: ["admin", "user"] },
  { label: "Templates", href: "/templates", icon: LayoutTemplate, roles: ["admin", "user"] },
  { label: "Analytics", href: "/analytics", icon: BarChart3, roles: ["admin"] },
  { label: "Audit Log", href: "/settings/audit", icon: ScrollText, roles: ["admin"] },
  { label: "Friday Spin!", href: "/spin-wheel", icon: Gift },
  { label: "Alerts", href: "/alerts", icon: AlertTriangle, roles: ["admin", "user"] },
  { label: "Staff Mailbox", href: "/staff-mailbox", icon: Inbox, roles: ["admin", "user", "sales", "telesales", "operative"] },
  { label: "Bulk Management", href: "/bulk-management", icon: Boxes, roles: ["admin"] },
  { label: "Admin", href: "/admin", icon: ShieldCheck, roles: ["admin"] },
  { label: "Settings", href: "/settings", icon: Settings, roles: ["admin"] },
];
