-- All PostgreSQL enum types for BuildStream CRM
-- Mirror Base44 spec entity enums exactly

CREATE TYPE user_role AS ENUM ('admin', 'user', 'operative', 'sales', 'telesales', 'contractor');
CREATE TYPE alert_type AS ENUM ('low_rating', 'message', 'reminder', 'email_bounce');
CREATE TYPE alert_status AS ENUM ('active', 'resolved', 'archived');
CREATE TYPE attendance_status AS ENUM ('present', 'absent', 'late', 'early_leave');
CREATE TYPE audit_action AS ENUM ('create', 'update', 'delete');
CREATE TYPE client_type AS ENUM ('domestic', 'commercial');
CREATE TYPE customer_status AS ENUM ('lead', 'active', 'inactive');
CREATE TYPE email_status AS ENUM ('valid', 'bounced', 'complained');
CREATE TYPE email_sequence_type AS ENUM ('new_lead', 'quote_not_booked', 'invoice_not_paid');
CREATE TYPE extra_work_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE invoice_type AS ENUM ('standard', 'deposit', 'progress', 'final', 'credit_note');
CREATE TYPE invoice_status AS ENUM ('draft', 'sent', 'part_paid', 'paid', 'overdue', 'cancelled');
CREATE TYPE discount_type AS ENUM ('none', 'percentage', 'fixed');
CREATE TYPE payment_method AS ENUM ('bank_transfer', 'credit_card', 'direct_debit');
CREATE TYPE integration_category AS ENUM ('Communications', 'Accounting', 'Payments', 'Calendar', 'Maps');
CREATE TYPE invited_dept AS ENUM ('telesales', 'team', 'field', 'subcontractor');
CREATE TYPE invited_status AS ENUM ('pending', 'accepted');
CREATE TYPE job_status AS ENUM ('scheduled', 'on_hold', 'in_progress', 'invoiced', 'awaiting_payment', 'completed', 'cancelled');
CREATE TYPE job_priority AS ENUM ('low', 'medium', 'high', 'urgent');
CREATE TYPE bid_status AS ENUM ('pending', 'accepted', 'rejected', 'withdrawn');
CREATE TYPE job_chat_role AS ENUM ('admin', 'operative', 'customer');
CREATE TYPE completion_satisfaction AS ENUM ('excellent', 'good', 'satisfactory', 'poor');
CREATE TYPE job_message_role AS ENUM ('office', 'contractor', 'client');
CREATE TYPE lead_source AS ENUM ('facebook', 'instagram', 'tiktok', 'twitter', 'linkedin', 'website_form', 'google_ads', 'referral', 'other');
CREATE TYPE lead_category AS ENUM ('web_forms', 'social', 'ppc', 'other');
CREATE TYPE lead_status AS ENUM ('new', 'contacted', 'qualified', 'appointment_booked', 'quoted', 'negotiation', 'won', 'lost');
CREATE TYPE lead_priority AS ENUM ('low', 'medium', 'high');
CREATE TYPE message_sender_type AS ENUM ('customer', 'admin');
CREATE TYPE message_status AS ENUM ('open', 'answered');
CREATE TYPE bonus_status AS ENUM ('pending', 'approved', 'paid');
CREATE TYPE prize_wheel_type AS ENUM ('crm', 'field');
CREATE TYPE quote_client_type AS ENUM ('residential', 'commercial');
CREATE TYPE quote_status AS ENUM ('draft', 'sent', 'accepted', 'declined', 'expired');
CREATE TYPE quote_template AS ENUM ('modern', 'classic', 'minimal');
CREATE TYPE receipt_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE reschedule_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE commission_period AS ENUM ('weekly', 'monthly');
CREATE TYPE related_type AS ENUM ('lead', 'quote', 'invoice');
CREATE TYPE service_category AS ENUM ('roofing', 'plumbing', 'electrical', 'painting', 'flooring', 'landscaping', 'demolition', 'renovation', 'concrete', 'carpentry', 'insulation', 'asbestos', 'general');
CREATE TYPE service_unit_type AS ENUM ('per_sqm', 'per_lm', 'per_hour', 'per_day', 'fixed', 'per_unit');
CREATE TYPE service_media_type AS ENUM ('ai_generated', 'uploaded', 'linked');
CREATE TYPE signup_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE subcontractor_status AS ENUM ('pending', 'active', 'inactive');
CREATE TYPE vehicle_type AS ENUM ('van', 'truck', 'pickup', 'car');
CREATE TYPE vehicle_status AS ENUM ('active', 'idle', 'maintenance', 'repair', 'offline');
CREATE TYPE website_status AS ENUM ('active', 'inactive', 'archived');
